/**:
  ros__parameters:
    wheel_radius: 0.033
    # 66mm by 2
    track_width: 0.160
    # 160mm
    motor_cmd_max: 265.0
    motor_cmd_per_rad_sec: 0.024
    encoder_ticks_per_rad:  651.8986469
    # 2^12 by 2pi
    collision_radius: 0.11
    # new params
    input_noise: 0.001
    slip_fraction: 0.001
    max_range: 1.5
    basic_sensor_variance: 0.001
    lidar_min_range: 0.12
    lidar_max_range: 3.5
    lidar_angle_increment: 0.01745329238474369
    lidar_samples: 360.0
    lidar_resolution: 1.0
    lidar_noise: 0.001