/**:
  ros__parameters:
    wheel_radius: 0.033
    # 66mm by 2
    track_width: 0.160
    # 160mm
    motor_cmd_max: 265.0
    motor_cmd_per_rad_sec: 0.024
    encoder_ticks_per_rad:  651.8986469
    # 2^12 by 2pi
    collision_radius: 0.11